spring.application.name=SE181979EmployeeService

server.port=8082
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MSS301_2026_PE;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=12345
# B?t bu?c ddl-auto=none theo ?? bài
spring.jpa.hibernate.ddl-auto=none

# C?u hình Swagger cho Spring Boot 3
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
