spring.application.name=SE181979FoodyGateway


server.port=8080

spring.cloud.gateway.mvc.routes[0].id=restaurant-service

spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081

spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/restaurants/**


spring.cloud.gateway.mvc.routes[1].id=food-service

spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8082

spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/foods/**


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
