spring.application.name=SE181979FoodyGateway


server.port=8080

spring.cloud.gateway.mvc.routes[0].id=[entityName1]-service

spring.cloud.gateway.mvc.routes[0].uri=http://localhost:[port1]

spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/[entities1]/**


spring.cloud.gateway.mvc.routes[1].id=[entityName2]-service

spring.cloud.gateway.mvc.routes[1].uri=http://localhost:[port2]

spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/[entities2]/**


springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
