spring.application.name=SE181979EmployeeGateway

server.port=8080

# C?u hình Route t? ??ng tr? v? Department Service (8081)
spring.cloud.gateway.routes[0].id=department-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/departments/**

# C?u hình Route t? ??ng tr? v? Employee Service (8082)
spring.cloud.gateway.routes[1].id=employee-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/employees/**

# C?u hình CORS ch?p nh?n k?t n?i t? m?i host theo yêu c?u
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
