spring.application.name=SE180211EmployeeGateway
server.port=8080
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Department Service
springdoc.swagger-ui.urls[0].url=/department-service/v3/api-docs
springdoc.swagger-ui.urls[1].name=Employee Service
springdoc.swagger-ui.urls[1].url=/employee-service/v3/api-docs
